# Generated by Django 5.0.7 on 2024-07-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archive', 'Archive'), ('pending', 'Pending'), ('rejected', 'Reject'), ('trash', 'Trash')], default='draft', max_length=10)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('topics', models.ManyToManyField(related_name='stories', to='user.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
