# Generated by Django 5.0.7 on 2024-07-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_avatar_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
