# Generated by Django 5.0.7 on 2024-07-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_story_delete_topic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
