# Generated by Django 5.0.7 on 2024-07-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='alijon', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
