# Generated by Django 5.0.7 on 2024-07-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
